---

- name: Install php70 ubuntu
  apt: name={{item}} state=latest update_cache=yes cache_valid_time=86400
  with_items:
    - php7.0
    - php7.0-mysql
    - libapache2-mod-auth-mysql
    - libapache2-mod-php7.0
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install php70 CentOS
  yum: name={{item}} state=present 
  with_items:
     - php70w
     - php70w-mysql
     - php70w-opcache
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'