---

- name: Install php56 ubuntu
  apt: name={{item}} state=latest update_cache=yes cache_valid_time=86400
  with_items:
    - php5.6
    - php5.6-mysql
    - libapache2-mod-auth-mysql
    - libapache2-mod-php5.6 
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install php56 CentOS
  yum: name={{item}} state=present 
  with_items:
     - php56w
     - php56w-mysql
     - php56w-opcache
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'