---

- name: Install php5 ubuntu
  apt: name={{item}} state=latest update_cache=yes cache_valid_time=86400
  with_items:
    - php5
    - php5-mysql
    - libapache2-mod-auth-mysql
    - libapache2-mod-php5
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 

- name: install php5 CentOS
  yum: name={{item}} state=present 
  with_items:
     - php55w
     - php55w-opcache
     - php55w-mysql
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'