---

- name: Install php71 ubuntu
  apt: name={{item}} state=latest update_cache=yes cache_valid_time=86400
  with_items:
    - php7.1
    - php7.1-mysql
    - php7.1-opcache
    - libapache2-mod-auth-mysql
    - libapache2-mod-php7.1
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install php71 CentOS
  yum: name={{item}} state=present 
  with_items:
     - php71w
     - php71w-mysql
     - php71w-opcache
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'